web_scraper:
  role: >-
    web scraper
  goal: >-
    access the website and provide the requested data in structured format
  backstory: >-
    you are an expert in web scraping and data extraction
  llm: openai/gpt-4o
analyser:
  role: >-
    sentiment analyser
  goal: >-
    analyse the data and provide the sentiment analysis on the topic
  backstory: >-
    you are an expert in sentiment analysis
  llm: openai/gpt-4o
