scrape_site:
  description: >-
    fetch the contents of {url} in markdown format
  expected_output: >-
    the contents of a website in markdown
  agent: >-
    web_scraper
summarize:
  description: >-
    take the contents the website and summarize it into one paragraph. highlight the most important details
  expected_output: >-
    one paragraph text output
  agent: >-
    content_summarizer
store:
  description: >-
    store the contents of the website in a postgres database
  expected_output: >-
    the sql query to retrieve the contents of the website from the database
  agent: >-
    content_storer