repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix]
        exclude: ^(agentstack/templates/|examples/|tests/fixtures/).*
    -   id: ruff-format
        exclude: ^(agentstack/templates/|examples/|tests/fixtures/).*
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        exclude: ^(agentstack/templates/|examples/|tests/fixtures/).*
