{%- if cookiecutter.structure.agents|length == 0 %}
default_agent:
    role: >
      give her a role
    goal: >
      add your goals
    backstory: >
      edit this backstory
    llm: openai/gpt-4
{%- endif %}

{%- for agent in cookiecutter.structure.agents %}
{{agent.name}}:
    role: >
      {{agent.role}}
    goal: >
      {{agent.goal}}
    backstory: >
      {{agent.backstory}}
    llm: {{agent.model}}
{%- endfor %}