[project]
name = "sentiment_analyser"
version = "0.0.1"
description = "This is the start of your AgentStack project."
authors = [
    { name = "Name <Email>" }
]
license = { text = "MIT" }
requires-python = ">=3.10"

dependencies = [
    "agentstack[crewai]>=0.2.5.1",
]