company_overview:
  description: >-
    As of {timestamp}, fetch the company overview for {company_name} usin real-time web search. Include
    company profile, industry, sector, CEO, headquarters location, employee count,  market
    capitalization and stock ticker symbol.
  expected_output: >-
    A structured company profile including: Company Profile, Industry, Sector, CEO,
    HQ Location, Employees, Market Cap and the stock ticker symbol.
  agent: >-
    web_researcher
financials_performance:
  description: >-
    As of {timestamp}, use real-time web search to extract financial performance data for {company_name},
    including Revenue (TTM), Net Income (TTM), Year-over-Year revenue growth, gross
    margin, and recent quarterly trends. Include any earnings trends or management
    commentary available.
  expected_output: >-
    A structured summary of financial metrics for {company_name}: Revenue (TTM), Net
    Income (TTM), YoY Revenue Growth, Gross Margin, Quarterly Trends, and Earnings
    Commentary.
  agent: >-
    web_researcher
competitive_benchmarking:
  description: >-
    As of {timestamp}, perform real-time web search to identify 3-5 peer companies in the same sector
    as {company_name}. Extract and compare key metrics such as P/E ratio, revenue,
    stock price, and market cap. Highlight any standout metrics where {company_name}
    outperforms or underperforms.
  expected_output: >-
    A comparison table of {company_name} and 3-5 peers showing P/E, revenue, price,
    and market cap. Highlight metrics where {company_name} stands out.
  agent: >-
    web_researcher
real_time_stock_snapshot:
  description: >-
    As of {timestamp}, convert {company_name} to its stock ticker symbol and retrieve a real-time stock
    snapshot using Dappier’s stock market data tool. Include current price with %
    daily change, volume, 52-week high/low, P/E ratio, EPS, dividend yield, and chart
    data for 1D, 5D, 1M, YTD, and 1Y in the query.
  expected_output: >-
    A structured stock summary for {company_name}, including:
    Price, % Daily Change, Volume, 52-Week High/Low, P/E Ratio, EPS, Dividend Yield,
    and chart data for 1D, 5D, 1M, YTD, 1Y.
  agent: >-
    stock_insights_analyst
news_and_sentiment:
  description: >-
    As of {timestamp}, convert {company_name} to its stock ticker symbol and fetch a real-time financial
    news stream using Dappier’s stock market data tool. Categorize the news by topic:
    Earnings, Analyst Ratings, Market Moves, Partnerships, and Legal/Regulatory in the
    query.
  expected_output: >-
    A categorized list of real-time financial news headlines
    for {company_name}, organized by topic: Earnings, Analyst
    Ratings, Market Moves, Partnerships, Legal/Regulatory in the query.
  agent: >-
    stock_insights_analyst
generate_investment_report:
  description: >-
    As of {timestamp}, compile a comprehensive, markdown-formatted investment report
    for {company_name} by synthesizing the outputs of all prior tasks: company overview,
    financial performance, competitive benchmarking, real-time stock snapshot, and
    categorized financial news. Include a concise AI-generated company summary,
    structured data tables, sentiment-tagged news, and a narrative insight section.
  expected_output: >-
    A markdown-formatted investment report containing:
      1. Quick AI summary of {company_name} (e.g., "Apple is a global tech leader…")
      2. Structured company profile: Industry, Sector, CEO, HQ, Employees, Market Cap
      3. Financial performance metrics: Revenue (TTM), Net Income (TTM), YoY Growth, Gross Margin, Trends
      4. Competitive benchmarking table: P/E, Revenue, Stock Price, Market Cap vs. 3–5 peers
      5. Real-time stock snapshot: Price, % Change, Volume, 52W High/Low, P/E, EPS, Dividend, charts
      6. Categorized news: Earnings, Analyst Ratings, Market Moves, Partnerships, Legal/Regulatory (with sentiment tags)
      7. Final 3-part insight section:
         - What's going on with {company_name}
         - Why it matters
         - Outlook (clearly marked as not financial advice)
  agent: >-
    report_analyst
  output_file: reports/{company_name}_investment_report.md
  create_directory: true
