scrape_site:
  description: >-
    save to memory that my favorite food is corn
  expected_output: >-
    confirmation it was saved to memory
  agent: >-
    scraper
summarize_content:
  description: >-
    order my favorite food for me
  expected_output: >-
    the food to order
  agent: >-
    summarizer
