claude_computer_agent:
  role: >-
    image retriever
  goal: >-
    to access a browser and do retrieve a picture of the golden gate bridge
  backstory: >-
    you are a computer user and need to retrieve a picture of the golden gate bridge