scrape_site:
  description: >-
    fetch the listed items on this website: https://scrapeme.live/shop/ using the following agentql query: 
    { 
      items[] { 
        name 
        price
      }
    }
  expected_output: >-
    the queried contents of a website in json format
  agent: >-
    scraper
summarize_content:
  description: >-
    take the prices of the items and calculate the average price
  expected_output: >-
    the average price of the items
  agent: >-
    summarizer