name: Mintlify Documentation Check
on:
  pull_request:
    paths:
      - 'docs/**'  # Only trigger on changes to docs directory
      - 'mint.json'  # Also trigger on mintlify config changes

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Mintlify
        run: npm install -g mintlify

      - name: Build documentation
        run: |
          cd docs
          mintlify build

      - name: Check build status
        run: |
          if [ $? -eq 0 ]; then
            echo "Documentation build successful!"
          else
            echo "Documentation build failed!"
            exit 1
          fi